const STOCK_MOVEMENT_TYPES = Object.freeze({
  STOCK_IN: "STOCK_IN",
  STOCK_OUT: "STOCK_OUT",
  ADJUSTMENT_IN: "ADJUSTMENT_IN",
  ADJUSTMENT_OUT: "ADJUSTMENT_OUT",
  TRANSFER_IN: "TRANSFER_IN",
  TRANSFER_OUT: "TRANSFER_OUT",
});

const STOCK_MOVEMENT_TYPE_VALUES = Object.values(STOCK_MOVEMENT_TYPES);

module.exports = {
  STOCK_MOVEMENT_TYPES,
  STOCK_MOVEMENT_TYPE_VALUES,
};
