const TRANSFER_STATUSES = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
});

const TRANSFER_STATUS_VALUES = Object.values(TRANSFER_STATUSES);

module.exports = {
  TRANSFER_STATUSES,
  TRANSFER_STATUS_VALUES,
};
